/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Comments {
  comment: string | null;
  date_posted: Timestamp | null;
  gp_id: string | null;
  id: number | null;
  read_by: string | null;
  reply_to: string | null;
  user_id: number | null;
}

export interface Riders {
  active: string | null;
  id: number | null;
  name: string | null;
  nation_id: number | null;
  number: number | null;
  substitute: string | null;
}

export interface RidersResults {
  gp_id: number | null;
  id: number | null;
  podium: string | null;
  points: number | null;
  races: number | null;
  rider_id: number | null;
}

export interface DB {
  comments: Comments;
  riders: Riders;
  riders_results: RidersResults;
}
